import jetBrains_Mono, { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrainsMono",
});

export const metadata = {
  title: "Sebastian Olarte",
  description: "Generated by create next app",
  icons: {
    icon: [{ url: "/assets/Logo.png", sizes: "48x48", type: "image/png" }],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`
          ${jetbrainsMono.variable}
          flex flex-col min-h-screen
          text-white relative overflow-x-hidden
        `}
        style={{
          backgroundColor: '#0c0c0c',
        }}
      >
        {/* Fondo con anillos concéntricos bien definidos */}
        <div className="absolute inset-0 -z-10 pointer-events-none">
          <div className="w-full h-full bg-concentric-rings opacity-20 animate-pulseSlow" />
        </div>

        {/* Contenido */}
        <Header className="z-10 relative" />
        <main className="flex-grow relative z-10">
          <StairTransition />
          <PageTransition>{children}</PageTransition>
        </main>
        <Footer className="mt-auto z-10 relative" />
      </body>
    </html>
  );
}
